# Generated by Django 5.2.11 on 2026-02-13 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
