# Generated by Django 5.1 on 2026-09-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='Student',
            new_name='student',
        ),
    ]
