# Generated by Django 5.1 on 2026-09-30 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='studentapp.conversation'),
        ),
    ]
