from pydantic import BaseModel
from typing import List

#defines the expected structure of the RAG/AI response
class RAGResponse(BaseModel):
    #The actual answer generated by the AI
    answer: str

    #list the sources to generate the answer
    sources: List[str]

    #confidence level of the answer
    confidence: str